/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StagnationRouteImport } from './routes/stagnation'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ExecutiveRouteImport } from './routes/executive'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as IndexRouteImport } from './routes/index'

const StagnationRoute = StagnationRouteImport.update({
  id: '/stagnation',
  path: '/stagnation',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutiveRoute = ExecutiveRouteImport.update({
  id: '/executive',
  path: '/executive',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRoute
  '/customers': typeof CustomersRoute
  '/executive': typeof ExecutiveRoute
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRoute
  '/stagnation': typeof StagnationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRoute
  '/customers': typeof CustomersRoute
  '/executive': typeof ExecutiveRoute
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRoute
  '/stagnation': typeof StagnationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRoute
  '/customers': typeof CustomersRoute
  '/executive': typeof ExecutiveRoute
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRoute
  '/stagnation': typeof StagnationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/collections'
    | '/customers'
    | '/executive'
    | '/reports'
    | '/sales'
    | '/stagnation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/collections'
    | '/customers'
    | '/executive'
    | '/reports'
    | '/sales'
    | '/stagnation'
  id:
    | '__root__'
    | '/'
    | '/collections'
    | '/customers'
    | '/executive'
    | '/reports'
    | '/sales'
    | '/stagnation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectionsRoute: typeof CollectionsRoute
  CustomersRoute: typeof CustomersRoute
  ExecutiveRoute: typeof ExecutiveRoute
  ReportsRoute: typeof ReportsRoute
  SalesRoute: typeof SalesRoute
  StagnationRoute: typeof StagnationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stagnation': {
      id: '/stagnation'
      path: '/stagnation'
      fullPath: '/stagnation'
      preLoaderRoute: typeof StagnationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executive': {
      id: '/executive'
      path: '/executive'
      fullPath: '/executive'
      preLoaderRoute: typeof ExecutiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectionsRoute: CollectionsRoute,
  CustomersRoute: CustomersRoute,
  ExecutiveRoute: ExecutiveRoute,
  ReportsRoute: ReportsRoute,
  SalesRoute: SalesRoute,
  StagnationRoute: StagnationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
